name: Deploy doc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          architecture: x64
          python-version: '3.10'
          cache: 'poetry'
      - name: Make doc
        run: |
          poetry env use "3.10"
          poetry install
          poetry run make -C doc dirhtml
          touch doc/_build/dirhtml/.nojekyll
        env:
          GTAGJS_IDS: ${{ secrets.GTAGJS_IDS }}
      - name: Deploy to GitHub Pages
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          build_dir: doc/_build/dirhtml
          github_token: ${{ secrets.GITHUB_TOKEN }}
